### ISSUE TITLE
Confirm non-configurable time periods

### ISSUE THREAD

**Issue by evilrobot-01** [tellor-io/tellor-pallet#10]
Certain time periods should not be configurable.

@oraclown could you possibly review the time period items of the `Config` trait in https://github.com/tellor-io/tellor-pallet/blob/03e8abd89635f41821c4837730a253c9d0d7e38a/src/lib.rs#L78 and note those which should **not** be configurable please?

**Comment by oraclown** [comment]
> tellor-pallet/src/lib.rs

Any in the original contracts that aren't configurable should be constants. Related: #18 
I've marked which ones seem (idk the original variable names / locations in files offhand) like they need to be constants rather than configurable:
```
/// The claim buffer time.
#[pallet::constant]
type ClaimBuffer: Get<<Self::Time as Time>::Moment>;

/// The claim period.
#[pallet::constant]
type ClaimPeriod: Get<<Self::Time as Time>::Moment>;

/// The hashing system (algorithm) to be used (e.g. keccak256).
type Hasher: Hash<Output = <Self as Config>::Hash> + TypeInfo;

/// Base amount of time before a reporter is able to submit a value again.
#[pallet::constant]
type ReportingLock: Get<TimestampOf<Self>>;

/// The dispute period.
#[pallet::constant]
type VoteRoundPeriod: Get<<Self::Time as Time>::Moment>;

/// The dispute period after a vote has been tallied.
#[pallet::constant]
type VoteTallyDisputePeriod: Get<<Self::Time as Time>::Moment>;

/// The withdrawal period.
#[pallet::constant]
type WithdrawalPeriod: Get<<Self::Time as Time>::Moment>;
```

**Comment by evilrobot-01** [comment]
The `Config::Time` associated type should be switched to the `UnixTime` trait which is more explicit, easing the definition of the time-based constants.
