### ISSUE TITLE
Dispute Fee Conversion

### ISSUE THREAD

**Issue by evilrobot-01** [tellor-io/tellor-pallet#17]
Related to #12, the dispute fee is calculated as a percentage of the stake amount in TRB, but will be charged in the currency/token configured by the parachain. We therefore need a mechanism for converting between percentage of stake amount to number of local tokens to then take as a dispute fee.

A suggestion is to use the same functionality [found within the staking contract](https://github.com/tellor-io/tellorFlex/blob/3b3820f2111ec2813cb51455ef68cf0955c51674/contracts/TellorFlex.sol#L26), which has it configured with a `query_id` which allows reporters to feed in the rate on an ongoing basis for rewards. It could also be added to the `register` function as an `Option<>` (alongside `stake_amount`) to allow the rate to be manually set if some value is provided (i.e. initial setup).

@oraclown it would be great to get your views on the above suggestion please!

**Comment by oraclown** [comment]
I agree that it should use the same functionality found in the original staking contract. There should be a minimum stake amount, and possibly a dollar target (or configurable currency of the pallet owner's choice).

**Comment by tkernell** [comment]
I agree that the dispute fee conversion should be done via a similar approach to the TellorFlex contract by configuring a dispute fee token `dispute_fee_token_query_id` when the pallet is deployed. Then the parachain should rely on both the `trb_query_id` and the `dispute_fee_token_query_id`, the former for calculating the current stake amount, and both for calculating the dispute fee. 

I'm not certain about adding it to the `register` function. This function is for passing relevant information to the EVM chain, correct? I don't believe the EVM chain needs to know this information. Although maybe I'm misunderstanding the objective of this function.

**Comment by tkernell** [comment]
Also, it should be noted that the dispute fee paid should be capped at the stake_amount.

In pseudocode:
```
current_stake_amount = max(minimum_stake_usd / trb_price, mimimum_stake_amount)

max_dispute_fee = current_stakeAmount * trb_price / dispute_fee_token_price

base_dispute_fee = max_dispute_fee / 10

if (first vote round) {
    dispute_fee_paid = base_dispute_fee * 2^(number of other open disputes on queryid)
} else {
   dispute_fee_paid = base_dispute_fee * 2^(this round number)
}

dispute_fee_paid = min(dispute_fee_paid, max_dispute_fee)
```

**Comment by tkernell** [comment]
I used `usd` in the example, but like Owen said, this could be denominated in any currency, as long the reported oracle data also uses that same currency, `{(trb, usd), (dot, usd)}`, or `{(trb, euro), (dot, euro)}`, etc.

**Comment by evilrobot-01** [comment]
> I agree that the dispute fee conversion should be done via a similar approach to the TellorFlex contract by configuring a dispute fee token `dispute_fee_token_query_id` when the pallet is deployed. Then the parachain should rely on both the `trb_query_id` and the `dispute_fee_token_query_id`, the former for calculating the current stake amount, and both for calculating the dispute fee. 
> 
> I'm not certain about adding it to the `register` function. This function is for passing relevant information to the EVM chain, correct? I don't believe the EVM chain needs to know this information. Although maybe I'm misunderstanding the objective of this function.

This could either be added as a Config item (i.e. configured when pallet first added to runtime, but can always be amended via a runtime upgrade, typically via governance once chain matures) or via a protected dispatchable function which is only callable by some configured origin (e.g. root/governance). A Config item would be my suggestion, unless you felt otherwise?

The register pallet function was primarily for registering with the EVM contracts yes, but also allowed additional fee config pertaining to EVM calls for convenience. This can always be split out as into its own function as required.

**Comment by oraclown** [comment]
> 

Config item for `dispute_fee_token_query_id` (or whatever you call it), so the parachain owner can pick the fee currency sounds good.

**Comment by evilrobot-01** [comment]
We are gearing up to tackle this issue, but I think it might be best to first handle the `trb_query_id` you mentioned in a separate issue. 

@tkernell just double checking that the pallet should also auto-adjust its (min) stake amount based on some configured currency target, as per the [tellorFlex contract](https://github.com/tellor-io/tellorFlex/blob/3b3820f2111ec2813cb51455ef68cf0955c51674/contracts/TellorFlex.sol#L351)?

**Comment by tkernell** [comment]
Yes that's fairly correct. Or to be more specific, in the tellorFlex contract, we had the stakeAmount unit adjust whenever someone calls `updateStakeAmount`, instead of having the contract automatically adjust the stake amount. We used this manual approach because:
1. `submitValue` depends on the `stakeAmount`
2. the updated `stakeAmount` is a function of the data submitted to `trb_query_id`. 3. It's possible that someone submits bad data to this query_id (unlikely but possible) which cannot be decoded as expected
4. If we automatically updated `stakeAmount` in `submitValue`, it would be possible for someone to freeze the `submitValue` function and completely freeze the oracle if bad data somehow made it through to `trb_query_id`

Therefore, we manually update `stakeAmount` whenever someone calls `updateStakeAmount`, which has some min and max checks.

**Comment by evilrobot-01** [comment]
Excellent, thanks! 

My thinking was to implement the `updateStakeAmount()` functionality via a [hook](https://paritytech.github.io/substrate/master/frame_support/traits/trait.Hooks.html#method.on_initialize), which could then be automatically called say every x blocks, negating the need for a manual call. The logic could also only use values say beyond the dispute period. Do you foresee any issue with this approach?

**Comment by tkernell** [comment]
I just wonder what would happen if somehow a bad value made it through past the 12 hour dispute period? Would this freeze the chain, or would it be able to handle this error via some kind of "try-catch" type of logic? If this scenario can be handled while allowing the system to continue, I think the auto-updates would be a desirable design.

**Comment by evilrobot-01** [comment]
We currently have the [`ValueConverter`](https://github.com/tellor-io/tellor-pallet/blob/46b9b35406ee2e81ccd1e0cbdfd8a71d0ee4bace/src/lib.rs#L184) config item which allows a converter function to be configured on the pallet to convert from bytes to some 'price' type, with a `None` value being returned if the conversion cannot be completed.

This is currently configurable as it seemed like there was no precise way to convert some submitted bytes for a `query_id` to a numerical value on chain without the data spec information and figured a parachain may have more insight into the types of data it may use and how to convert/support. An example of coordinates comes to mind. The `ValueConverter` is currently only used when a feed has a `price_threshold` set and the submitted values need to be converted to a price to determine whether the threshold has been exceeded.

We can easily internalise this conversion so it is no longer configurable and perhaps attempt to convert based on some rules, but this would still be best efforts. An internal converter could also perhaps be a fallback when no additional converter is specified.

Any other suggestions would be appreciated!

**Comment by evilrobot-01** [comment]
After Friday's call, the approach for implementing this should follow https://github.com/tellor-io/tellor-pallet/pull/46 where the dispute fee is saved to a `DisputeFee` storage item, updated regularly via the `update_stake_amount` function based on submitted oracle value.

It is therefore probably easiest to base a PR for this issue on #46 or wait until it is merged.
