### ISSUE TITLE
Standardise on hash(para_id, query_id, timestamp) for dispute id

### ISSUE THREAD

**Issue by evilrobot-01** [tellor-io/tellor-pallet#19]
Smart contracts have been updated to just use `hash(para_id, query_id, timestamp)` for dispute id, removing the need for using an integer. Pallet should be updated to follow this approach.

@oraclown please kindly confirm you are happy with this so we can proceed.

**Comment by oraclown** [comment]
> Smart contracts have been updated to just use hash(para_id, query_id, timestamp) for dispute id, removing the need for using an integer. Pallet should be updated to follow this approach.
> 
> @oraclown please kindly confirm you are happy with this so we can proceed.

Yes, thank you! The equivalent of this solidity: `bytes32 _disputeId = keccak256(abi.encode(parachain.id, _queryId, _timestamp));`

**Comment by evilrobot-01** [comment]
Updating `dispute_id` to a hash type, the same as the identifier used for the vote, has a knock-on effect to vote rounds, effectively making the return type of [`get_vote_rounds`](https://github.com/tellor-io/tellor-pallet/blob/0d5eb91197722547acc6ad97ea88f7bf0f4d0b15/src/impls.rs#L861) a vector of the same hash depending on the number of rounds.

Could the `get_vote_rounds` function perhaps be updated to the following, which obviously alters the RPC API somewhat:

```
/// Returns the voting rounds for a given dispute identifier.
/// # Arguments
/// * `dispute_id` - Identifier for a dispute.
/// # Returns
/// The number of vote rounds for the dispute identifier.
pub fn get_vote_rounds(dispute_id: DisputeIdOf<T>) -> u32 {
  <VoteRounds<T>>::get(dispute_id)
}
```

Where the [`VoteRounds`](https://github.com/tellor-io/tellor-pallet/blob/0d5eb91197722547acc6ad97ea88f7bf0f4d0b15/src/lib.rs#L313-L320) storage item is updated to store the number of vote rounds by `dispute_id`:
```
#[pallet::storage]
pub type VoteRounds<T> = StorageMap<_, Blake2_128Concat, DisputeIdOf<T>, u32, ValueQuery>;
```

The [`VoteInfo`](https://github.com/tellor-io/tellor-pallet/blob/0d5eb91197722547acc6ad97ea88f7bf0f4d0b15/src/lib.rs#L312) storage item also then needs updating to track information per vote round, so we could use a `StorageDoubleMap`, essentially modelled as `(dispute_id, vote_round) = Vote`:

```
#[pallet::storage]
pub type VoteInfo<T> = StorageDoubleMap<_, Blake2_128Concat, DisputeIdOf<T>, Blake2_128Concat, u32, VoteOf<T>>;
```

If you think that going down this route is acceptable, additional optimisations can potentially be made to reduce the number of storage items required for the dispute/voting process within the pallet. I would suggest that a proposed PR be used to explore this, rather than comments here. Please let me know your thoughts and I can prepare something...

**Comment by oraclown** [comment]
> Updating `dispute_id` to a hash type, the same as the identifier used for the vote, has a knock-on effect to vote rounds, effectively making the return type of [`get_vote_rounds`](https://github.com/tellor-io/tellor-pallet/blob/0d5eb91197722547acc6ad97ea88f7bf0f4d0b15/src/impls.rs#L861) a vector of the same hash depending on the number of rounds.
> 
> Could the `get_vote_rounds` function perhaps be updated to the following, which obviously alters the RPC API somewhat:
> 
> ```
> /// Returns the voting rounds for a given dispute identifier.
> /// # Arguments
> /// * `dispute_id` - Identifier for a dispute.
> /// # Returns
> /// The number of vote rounds for the dispute identifier.
> pub fn get_vote_rounds(dispute_id: DisputeIdOf<T>) -> u32 {
>   <VoteRounds<T>>::get(dispute_id)
> }
> ```
> 
> Where the [`VoteRounds`](https://github.com/tellor-io/tellor-pallet/blob/0d5eb91197722547acc6ad97ea88f7bf0f4d0b15/src/lib.rs#L313-L320) storage item is updated to store the number of vote rounds by `dispute_id`:
> 
> ```
> #[pallet::storage]
> pub type VoteRounds<T> = StorageMap<_, Blake2_128Concat, DisputeIdOf<T>, u32, ValueQuery>;
> ```
> 
> The [`VoteInfo`](https://github.com/tellor-io/tellor-pallet/blob/0d5eb91197722547acc6ad97ea88f7bf0f4d0b15/src/lib.rs#L312) storage item also then needs updating to track information per vote round, so we could use a `StorageDoubleMap`, essentially modelled as `(dispute_id, vote_round) = Vote`:
> 
> ```
> #[pallet::storage]
> pub type VoteInfo<T> = StorageDoubleMap<_, Blake2_128Concat, DisputeIdOf<T>, Blake2_128Concat, u32, VoteOf<T>>;
> ```
> 
> If you think that going down this route is acceptable, additional optimisations can potentially be made to reduce the number of storage items required for the dispute/voting process within the pallet. I would suggest that a proposed PR be used to explore this, rather than comments here. Please let me know your thoughts and I can prepare something...

Yes, those changes make sense. PR exploring further sounds good.

I need to check if similar changes can be made in the governance contract: [#16](https://github.com/tellor-io/tellor-parachain-contracts/issues/16)

**Comment by oraclown** [comment]
Talking with @tkernell more about this, will get back to you with more thoughts or a PR on the contracts side

**Comment by evilrobot-01** [comment]
Cool, will link a draft PR on the pallet side once presentable, so we can try to align on the approach.

**Comment by tkernell** [comment]
> Updating `dispute_id` to a hash type, the same as the identifier used for the vote, has a knock-on effect to vote rounds, effectively making the return type of [`get_vote_rounds`](https://github.com/tellor-io/tellor-pallet/blob/0d5eb91197722547acc6ad97ea88f7bf0f4d0b15/src/impls.rs#L861) a vector of the same hash depending on the number of rounds.
> 
> Could the `get_vote_rounds` function perhaps be updated to the following, which obviously alters the RPC API somewhat:
> 
> ```
> /// Returns the voting rounds for a given dispute identifier.
> /// # Arguments
> /// * `dispute_id` - Identifier for a dispute.
> /// # Returns
> /// The number of vote rounds for the dispute identifier.
> pub fn get_vote_rounds(dispute_id: DisputeIdOf<T>) -> u32 {
>   <VoteRounds<T>>::get(dispute_id)
> }
> ```
> 
> Where the [`VoteRounds`](https://github.com/tellor-io/tellor-pallet/blob/0d5eb91197722547acc6ad97ea88f7bf0f4d0b15/src/lib.rs#L313-L320) storage item is updated to store the number of vote rounds by `dispute_id`:
> 
> ```
> #[pallet::storage]
> pub type VoteRounds<T> = StorageMap<_, Blake2_128Concat, DisputeIdOf<T>, u32, ValueQuery>;
> ```
> 
> The [`VoteInfo`](https://github.com/tellor-io/tellor-pallet/blob/0d5eb91197722547acc6ad97ea88f7bf0f4d0b15/src/lib.rs#L312) storage item also then needs updating to track information per vote round, so we could use a `StorageDoubleMap`, essentially modelled as `(dispute_id, vote_round) = Vote`:
> 
> ```
> #[pallet::storage]
> pub type VoteInfo<T> = StorageDoubleMap<_, Blake2_128Concat, DisputeIdOf<T>, Blake2_128Concat, u32, VoteOf<T>>;
> ```
> 
> If you think that going down this route is acceptable, additional optimisations can potentially be made to reduce the number of storage items required for the dispute/voting process within the pallet. I would suggest that a proposed PR be used to explore this, rather than comments here. Please let me know your thoughts and I can prepare something...

I think these changes make sense and are a worthy improvement on how we store the dispute data

**Comment by evilrobot-01** [comment]
Great, thanks!

The linked PR now has a complete implementation along with required changes to the RPC API.

I will look over again and mark the PR as ready for review.
