### ISSUE TITLE
Execute vote function handles all fee transfers

### ISSUE THREAD

**Issue by oraclown** [tellor-io/tellor-pallet#36]
- `execute_vote` should just take the necessary identifier and the vote result, then handle whatever fee transfers are needed

**Comment by evilrobot-01** [comment]
A PR to resolve this issue will:
- remove `vote_round` parameter from `execute_vote(`..)
- merging the `report_slash`, `report_invalid_dispute` & `slash_dispute_initiator` functions into a single `report_vote_executed` dispatchable function

A seperate PR may be needed to https://github.com/tellor-io/tellor-parachain-contracts/blob/main/src/Parachain.sol to update the call indexes as appropriate.
