### ISSUE TITLE
Feat: oracle user disputes

### ISSUE THREAD

**Issue by evilrobot-01** [tellor-io/tellor-pallet#5]
Suggestion for the future: currently only an oracle reporter can begin a dispute, as a verified account is required on the staking chain to be used in the case of the dispute being successful and the original reporter being slashed in favour of the dispute initator.

A dispatchable function could be added which allows a verified oracle user (i.e. has previously submitted tips/funded a feed) to simply flag a quistionable value for dispute, as they may not have an account on the staking chain to receive any slash. Reporters could then monitor/query flagged values.

**Comment by tkernell** [comment]
I think it's fairly important for the oracle security to allow anyone to dispute data. We want to incentivize people to monitor data and dispute any bad data in order to earn a reward. Would it make sense to include the user's EVM address as an input to the `begin_parachain_dispute` function?

**Comment by evilrobot-01** [comment]
We could definitely do that.

Perhaps even make it an `Option<Address>` parameter, where the corresponding address is looked up from staker details for the dispute initiator if `None` is provided, saving a reporter the need to provide a value.

The risk of providing an invalid/unverified address would obviously be on the dispute initiator though...

**Comment by tkernell** [comment]
I like the idea of making it a optional param, which at least limits that bad address risk some for registered stakers
