### ISSUE TITLE
Update tally date when vote tallied by controller contracts

### ISSUE THREAD

**Issue by oraclown** [tellor-io/tellor-pallet#53]
- When `tallyVotes` is called on the governance contract on the evm-compatible parachain, that time and outcome needs to be passed to the oracle consumer chain, or else one can't open new vote rounds from the oracle consumer parachain side, as the `tally_date` will remain `0` for [this check](https://github.com/tellor-io/tellor-pallet/blob/main/src/lib.rs#L1189).
- Currently, this is implemented in `reportVoteTallied` in [#43](https://github.com/tellor-io/tellor-parachain-contracts/pull/43), with a similar pattern to the other functions that pass data and updates back to the oracle consumer side
- If a corresponding function in the pallet already exists, then what's the correct call index that `reportVoteTallied` should use? If not, such a function is needed on the pallet side, no?

**Comment by evilrobot-01** [comment]
No problem, will add. Just to check, the current smart contract function isnt passing the time only the outcome, so we are to use the current time as received on the pallet? 

PS - there have been a few changes to pallet indexes lately with a few additional functions being added, so will create an issue to update them in the contracts once finalised.

**Comment by oraclown** [comment]
> No problem, will add. Just to check, the current smart contract function isnt passing the time only the outcome, so we are to use the current time as received on the pallet?
> 
> PS - there have been a few changes to pallet indexes lately with a few additional functions being added, so will create an issue to update them in the contracts once finalised.

- Using the current time once received by pallet is good.
- Here's the issue to update the call indexes on the contracts side: https://github.com/tellor-io/tellor-parachain-contracts/issues/44
